// scripts/sample-prompts.mjs
//
// Hand-authored video prompts for the pre-generated sample set:
// 3 beats (discovery -> calling -> eye contact) x 5 versions
// (Original + 4 era remixes) = 15 clips, generated by Omni Flash
// with the public/images reference art as the style anchor.

export const COMMON_STYLE =
  `Use the 8 provided reference images as the primary visual style references. ` +
  `Match their overall art direction, character proportions, line quality, color ` +
  `palette, background texture, lighting mood, and magical effect style. Do not ` +
  `copy any exact composition from the reference images; create a new original ` +
  `scene that feels like it belongs in the same visual universe.\n\n` +
  `Keep the same shy 12-year-old girl protagonist and the same slim 12-year-old ` +
  `boy across all clips. The boy has narrow shoulders, messy spiky light-gold ` +
  `hair that feels like a small crooked crown, vivid green eyes, and a red ` +
  `writing tool. His wheelchair or mobility chair may be visible naturally, but ` +
  `it should not be the focus of the scene.\n\n` +
  `Animated cinematic storybook style, warm magical realism, soft expressive ` +
  `character acting, gentle camera movement. Magical word effects should appear ` +
  `as abstract glowing handwritten strokes, not readable text.\n\n` +
  `No subtitles, no captions, no logos, no watermark, no readable on-screen text.`

// The three story moments every version renders, in order.
export const BEAT_KEYS = ['discovery', 'calling', 'eye-contact']

// dialogue: what the girl whispers in this version — swapped into the beat's
// spoken segment for TTS so voices match what the clip implies (null = keep
// the excerpt's original line).
export const VERSIONS = [
  {
    id: 'original',
    label: 'Original',
    dialogue: null,
    prompts: [
      `8-second video, 16:9. A quiet school courtyard in a small Southern town. ` +
        `Several outdoor lunch tables are messy with bird droppings, but one table ` +
        `is strangely clean. A shy girl notices it and stops. At the clean table, a ` +
        `slim blond boy reads a folded newspaper and casually twirls a red pen. ` +
        `Camera starts wide, then slowly pushes in from the girl's point of view. ` +
        `Mood: curious, ordinary but slightly uncanny. Audio: distant schoolyard ` +
        `ambience, paper rustle, soft pen tapping.`,
      `8-second video, 16:9. The girl steps closer to the clean lunch table, ` +
        `nervous but determined. The boy keeps reading the newspaper, not looking ` +
        `at her, the red pen spinning between his fingers. Over-the-shoulder camera ` +
        `from behind the girl. She whispers, "Pumpernickel?" The pen stops ` +
        `mid-twirl, and the courtyard sound gently fades. Mood: quiet tension, ` +
        `comic awkwardness, first contact.`,
      `8-second video, 16:9. Close-up sequence. The boy slowly lifts his head from ` +
        `the newspaper and looks directly at the girl. His eyes are the greenest ` +
        `vivid green, like fresh neon ink, but still gentle and human. Abstract ` +
        `glowing handwritten strokes drift around the girl for a moment, suggesting ` +
        `hidden words and magic. Camera slowly pushes into his eyes. Audio: soft ` +
        `shimmer, paper flutter, held breath. Mood: wonder, surprise, the beginning ` +
        `of friendship.`,
    ],
  },
  {
    id: 'joseon',
    label: 'Joseon Korea',
    dialogue: '검은 보리떡?',
    prompts: [
      `8-second video, 16:9. A Joseon-era village schoolyard near a small seodang. ` +
        `Several low wooden platforms are marked by bird droppings, but one low ` +
        `table is perfectly clean. A shy girl in simple Joseon clothing notices it. ` +
        `A slim boy sits there reading a folded notice, twirling a red brush handle ` +
        `between his fingers. A crafted wooden wheeled chair is naturally visible ` +
        `beside the table. Camera glides slowly through warm afternoon dust. Mood: ` +
        `historical, delicate, mysterious.`,
      `8-second video, 16:9. The girl approaches the clean wooden table, holding ` +
        `her sleeve close. The boy does not look up, still reading the folded ` +
        `paper. His red brush handle spins lightly between his fingers. The girl ` +
        `whispers in Korean, "검은 보리떡?" The brush stops. Wind moves the paper ` +
        `edge. Audio: distant market sounds, soft wind, brush tap, sudden hush. ` +
        `Mood: strange, tender, slightly humorous.`,
      `8-second video, 16:9. The boy slowly raises his head. His vivid jade-green ` +
        `eyes catch the sunlight like polished glass. Around the girl, abstract ` +
        `glowing brushlike strokes float briefly in the air, inspired by old Korean ` +
        `calligraphy but not readable. Camera moves from medium shot into a ` +
        `close-up of his eyes. Audio: tiny bell-like shimmer, paper rustle, wind ` +
        `through wooden eaves. Mood: magical recognition, quiet awe.`,
    ],
  },
  {
    id: 'medieval',
    label: 'Medieval Europe',
    dialogue: null,
    prompts: [
      `8-second video, 16:9. A medieval town market beneath castle walls. Several ` +
        `rough wooden tables are stained by birds, but one long table is clean. A ` +
        `shy young girl in a simple cloak notices the clean table. A slim blond boy ` +
        `sits there reading a folded town notice, twirling a red quill pen. A ` +
        `handcrafted wheeled chair is partly visible near him. Camera slowly tracks ` +
        `through the busy market into a quieter pocket of space. Mood: old-world, ` +
        `curious, enchanted.`,
      `8-second video, 16:9. The girl steps closer through the medieval market ` +
        `noise. The boy keeps reading, his messy light-gold hair catching sunlight ` +
        `like a crooked little crown. He twirls the red quill without looking at ` +
        `her. She whispers, "Pumpernickel?" The quill stops. Market sounds soften ` +
        `as if the world is listening. Audio: distant bells, footsteps, parchment ` +
        `rustle, soft quill tap.`,
      `8-second video, 16:9. The boy lifts his head from the parchment and looks ` +
        `at the girl. His eyes glow a vivid green like light passing through ` +
        `emerald stained glass. Abstract illuminated-manuscript-like strokes drift ` +
        `around the girl, glowing softly but not forming readable letters. Camera ` +
        `pushes into his face, then holds on the eye contact. Audio: faint choral ` +
        `shimmer, parchment flutter. Mood: secret magic, wonder, recognition.`,
    ],
  },
  {
    id: 'k90s',
    label: '1990s Korea',
    dialogue: '펌퍼니클?',
    prompts: [
      `8-second video, 16:9. A 1990s Korean school snack shop street with plastic ` +
        `tables, a public phone, old signs, and warm late-afternoon light. Several ` +
        `outdoor tables are messy from birds, but one plastic table is unusually ` +
        `clean. A shy schoolgirl with a backpack notices it. A slim boy sits there ` +
        `reading a sports newspaper, twirling a red Monami-style pen. A compact ` +
        `motorized wheelchair is naturally visible. Camera has a gentle VHS-era ` +
        `texture. Mood: nostalgic, curious.`,
      `8-second video, 16:9. The girl approaches the clean plastic table in front ` +
        `of the snack shop. The boy keeps reading the newspaper, red pen spinning ` +
        `between his fingers. Background details suggest 1990s Korea: cassette ` +
        `shop ambience, school uniforms, plastic chairs, snack steam. She ` +
        `whispers, "펌퍼니클?" The pen clicks and stops. Audio: distant cassette ` +
        `music, traffic hum, paper rustle, sudden quiet.`,
      `8-second video, 16:9. The boy slowly looks up from the newspaper. His eyes ` +
        `shine a vivid green like a fresh fluorescent marker. The VHS-like image ` +
        `gently flickers as abstract glowing handwritten strokes float around the ` +
        `girl, suggesting magical words without readable text. Camera moves into a ` +
        `close-up, holding the surprised eye contact. Audio: soft electric shimmer, ` +
        `snack shop ambience fading back in. Mood: nostalgic wonder, first ` +
        `friendship.`,
    ],
  },
  {
    id: 'space',
    label: 'Space Colony',
    dialogue: null,
    prompts: [
      `8-second video, 16:9. A distant-future space colony cafeteria inside a ` +
        `glass habitat dome. Outside, a terraformed landscape glows faintly. Most ` +
        `tables are smudged with mineral dust from small pollinator drones, but one ` +
        `table is perfectly clean. A shy girl in a light colony suit notices it. A ` +
        `slim blond boy reads a floating holo-newspaper and twirls a red stylus. A ` +
        `sleek hover wheelchair is naturally visible. Camera drifts slowly, low ` +
        `gravity feeling. Mood: futuristic, quiet, magical.`,
      `8-second video, 16:9. The girl moves closer through the colony cafeteria, ` +
        `passing soft blue life-support lights and quiet food machines. The boy ` +
        `keeps reading the holo-newspaper, red stylus rotating weightlessly between ` +
        `his fingers. She whispers, "Pumpernickel?" The stylus freezes in midair ` +
        `for a beat. The holo-newspaper flickers with abstract, unreadable light ` +
        `patterns. Audio: low habitat hum, distant drone chirps, soft magnetic ` +
        `click.`,
      `8-second video, 16:9. The boy slowly lifts his head from the holo-newspaper ` +
        `and looks directly at the girl. His eyes glow vivid green like the first ` +
        `plants growing under a terraforming dome. Around the girl, abstract ` +
        `AR-like handwritten light trails drift in the air, suggesting hidden words ` +
        `but not readable text. Camera slowly pushes into the eye contact. Audio: ` +
        `gentle electronic shimmer, habitat hum, a soft breath. Mood: cosmic ` +
        `wonder, human warmth, the beginning of connection.`,
    ],
  },
]
